// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgXUN-_nfO7i3Ymo_JwR3kNGTrUBg0zXM',
    appId: '1:857891926241:web:171dfc4aa2776207e887a0',
    messagingSenderId: '857891926241',
    projectId: 'parkinson-c9184',
    authDomain: 'parkinson-c9184.firebaseapp.com',
    storageBucket: 'parkinson-c9184.appspot.com',
    measurementId: 'G-85X8GZ7YSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-8K_0MOJ2bw_CqBvMJeq4I30sUQ9IU48',
    appId: '1:857891926241:android:eb50675a067f979ce887a0',
    messagingSenderId: '857891926241',
    projectId: 'parkinson-c9184',
    storageBucket: 'parkinson-c9184.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEAcmPelGi-smZIqTOxTZnx4-NRkMc-RA',
    appId: '1:857891926241:ios:4735ac6fd2b2b18ce887a0',
    messagingSenderId: '857891926241',
    projectId: 'parkinson-c9184',
    storageBucket: 'parkinson-c9184.appspot.com',
    iosBundleId: 'com.example.myworkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEAcmPelGi-smZIqTOxTZnx4-NRkMc-RA',
    appId: '1:857891926241:ios:efb96a10696716d1e887a0',
    messagingSenderId: '857891926241',
    projectId: 'parkinson-c9184',
    storageBucket: 'parkinson-c9184.appspot.com',
    iosBundleId: 'com.example.myworkingApp.RunnerTests',
  );
}
